openapi: 3.0.0
info:
  title: Agent Nudging API
  description: API for managing nudging agents and interactions
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local dev server

paths:
  /nudges:
    get:
      summary: List all nudges
      responses:
        '200':
          description: A list of nudges
    post:
      summary: Create a new nudge
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '201':
          description: Nudge created

  /nudges/{id}:
    get:
      summary: Get a single nudge
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Nudge details
    delete:
      summary: Delete a nudge
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted successfully
